
String Html_Config() {

  String html = "<html>"
  "<head>"
  "<meta id=\"Viewport\" name=\"viewport\" width=\"initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no\">"
  "<title>Slider</title>"
  "<style>"
  "html, body { margin: 0; padding: 0; font-size: 5vw; font-family: sans-serif; }"
  "* { font-size: inherit; }"
  "td { padding: 1vw; }"
  "button { width: 25vw; }"
  "input[type=number] { width: 25vw; }"
  "</style>"
  "</head>"
  "<body>"
  "<form action=\"\" method=\"post\">"
  "<table border=\"0\" style=\"width: 100vw;\">"
  "  <tr>"
  "   <td colspan=\"2\"><strong>Slider</strong><hr/></td>"
  " </tr>"
  " <tr>"
  "   <td>Distance</td>"
  "   <td>"
  "     <input type=\"number\" step=\"any\" name=\"distance\" value=\"" + String(distance) + "\">"
  "     <select name=\"distance_mm_multiplier\">"
  "       <option value=\"1\" " + String(distance_mm_multiplier == (float)1 ? "selected=\"true\"" : "") + ">millimeters</option>"
  "       <option value=\"10\" " + String(distance_mm_multiplier == (float)10 ? "selected=\"true\"" : "") + ">centimeters</option>"
  "     </select>"
  "   </td>"
  " </tr>"
  " <tr>"
  "   <td>Time</td>"
  "   <td><input type=\"number\" step=\"any\" name=\"duration\" value=\"" + String(duration) + "\">"
  "     <select name=\"duration_sec_multiplier\">"
  "       <option value=\"1\" " + String(duration_sec_multiplier == (float)1 ? "selected=\"true\"" : "") + ">seconds</option>"
  "       <option value=\"60\" " + String(duration_sec_multiplier == (float)60 ? "selected=\"true\"" : "") + ">minutes</option>"
  "     </select>"
  "   </td>"
  " </tr>"
  " <tr>"
  "   <td>Direction</td>"
  "   <td>"
  "     <select name=\"direction\">"
  "       <option value=\"1\">A to B</option>"
  "       <option value=\"-1\">B to A</option>"
  "     </select>"
  "   </td>"
  " </tr>"
  " <tr>"
  "   <td></td>"
  "   <td>"
  "     <a href=\"/gotoa\">&nbsp;<<<&nbsp;</a>"
  "     <button type=\"submit\">Go</button>"
  "     <a href=\"/gotob\">&nbsp;>>>&nbsp;</a>"
  "   </td>"
  " </tr>"
  "</table>"
  "</form>"
  "</body>"
  "</html>";

  return html;
}

